[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "jupiterli"
version = "0.6.1"
dependencies = [
   "typer",
   "paho-mqtt"
]

[project.scripts]
jupiterli = "jupiterli.cli:main" # jupiterli backend

[tool.setuptools.packages.find]
include = ["jupiterli*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
jupiterli = ["docker/*"]
